### ISSUE TITLE
It does not support Google Cloud VM

### ISSUE THREAD

**Issue by isyume** [MeowLove/Network-Reinstall-System-Modify#13]
As title said, this script does not support google cloud. No matter what the initial system is, after use this script it will be loss connection to ssh.

**Comment by isyume** [comment]
It seems that the subnet mask is wrong. Execute the ifconfig command in Google Cloud it shows me 255.255.255.255

**Comment by MeowLove** [comment]
Google Cloud uses a mask of 255.255.255.255, which is usually not a gateway and mask that normal Linux systems can recognize.Similar cases, such as Online.net's, fail over IP in virtual machines, which is not the correct mask and gateway.
This is because the service provider remaps the gateway in its own internal network. You need to calculate the network segment and mask manually to get the first gateway address.

谷歌云使用了255.255.255.255的掩码，通常情况下，这不是正常的Linux系统所能识别的网关和掩码。相似的案例，例如Online.net家，在虚拟机中的故障转移IP，他并不是正确的掩码和网关。
这是因为服务商在自己的内部网络，对网关进行了重映射。你需要通过手动计算网络段，掩码，获得出第一个网关地址。
