### ISSUE TITLE
请上传关键源码，空项目是不合适的。

### ISSUE THREAD

**Issue by Argon-Pub** [MeowLove/Network-Reinstall-System-Modify#2]

**Comment by MeowLove** [comment]
In order to make more users understand your description, it is recommended that all Issues be submitted in English.（為了使得更多用戶明白您的描述，建議所有Issues使用英文提交。）

Thank you very much, the latest stable version of V2.0.1 has been released.

Starting with V2.0.1, [Network-Reinstall-System-Modify] provides manual installation and remote network ISO installation. This is a new version of the experience.

The V1.0.1 version is called the beta version, which is unstable and the function is not complete. In order to avoid confusion caused by more people touching the beta, there is no upload.
