### ISSUE TITLE
无限循环，无法完成重装

### ISSUE THREAD

**Issue by yfzuix** [MeowLove/Network-Reinstall-System-Modify#7]
已经试过阿里云ecs、轻量云，腾讯云cvm，Vultr和本地虚拟机，试用大佬的脚本重装系统，连续跑三天三夜还无法完成重装，一直在重复那几个弹窗和流程

**Comment by MeowLove** [comment]
已经修复。之前我的博客和服务器挂了，自然无法成功。

原因是：当镜像源无法连接时，系统会不断尝试镜像源，去安装系统，但是我服务器炸了，就一直循环。

Has been repaired. I lost my blog and server before, so I couldn't succeed.

The reason is: when the mirror source can't be connected, the system will keep trying to mirror the source to install the system, but my server explodes and keeps circulating.

MeowLove
